[package]
name = "thermal"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
escpos = { version = "0.16.0", features = ["full"] }
rusb = "0.9.4"
serde = {version = "1.0.219", features=["derive"]}
serde_json = "1.0.141"
